name: Swift

on: [push]

jobs:
  build:

    runs-on: macos-15

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: "16.0"
    - name: Build
      run: xcodebuild
